=== make-update-alternatives-for-java

make-alternatives-for-java.sh: a Bash wrapper for Debian update-alternatives that
creates and removes the symbolic links comprising the Debian alternatives
for executables associated with with a Java JDK.

==== The problem
There are differences as to what executable is where and available in what
version of a JDK.  The 1.8 JDK bin directory contains 48 executables vs the 35
in the bin directory of JDK 11.  There are also the associated MAN pages that have to
be slaved to their corresponding executable. To install, remove, and switch between
alternatives would be a daunting and error prone manual task.  Hence, the
motivation for development of this wrapper for update-alternatives.

make-update-alternatives-for-java automates the installation, removal, and
switching of alternatives for user installed JDKs. It scans the bin and the
jre/bin subdirectories of a given JDK home directory (java-home-path; see below)
for files that are executable. MAN pages in man1 ending in .1 or .1.gz if any
will be slaved to their associated executable if the action requested is *install*.

* Sample JDK executable locations/availability:
+
[%header, cols="<,^,^,^,^,^,^"]
|===
^|Name
|JDK 11.0 +
bin
|JDK 11.0 +
lib
|JDK 1.8 +
jre/bin
|JDK 1.8 +
bin
|JDK 1.8 +
jre/lib
| JDK 1.8 +
lib

|java       | 1 | - | 1 | 2 | - | -
|keytool    | 1 | - | 1 | 2 | - | -
|javac      | 1 | - | - | 1 | - | -
|jlink      | 1 | - | - | - | - | -
|jshell     | 1 | - | - | - | - | -
|pack200    | 1 | - | 1 | 2 | - | -
|unpack200  | 1 | - | 1 | 2 | - | -
|xjc        | - | - | 1 | 2 | - | -
|jexec      | - | 1 | - | - | 1 | 2
|===
+
Executables in jre/bin have precedence over bin as indicated by the rank of 1 in
the table.
+
** jexec only appears in lib.
** java and keytool appear in 2 locations in JDK 1.8
** pack200 will be deprecated in a future JDK.
** xjc is missing in JDK 11 because the Java EE and CORBA modules were removed
  and are now available as libraries.
** jlink and jshell appear only JDK 11.

Directory Layouts of the Two JDKs:

* JDK 11
+
----
/opt/java/jdk11.0
├── bin
├── conf
├── include
├── jmods
├── legal
├── lib
├── LICENSE
├── man
├── readme.txt
└── release
----
* JDK 1.8
+
----
/opt/java/jdk1.8.0
├── bin
├── COPYRIGHT
├── include
├── javafx-src.zip
├── jre
├── lib
├── LICENSE
├── man
├── README.html
├── release
├── src.zip
├── THIRDPARTYLICENSEREADME-JAVAFX.txt
└── THIRDPARTYLICENSEREADME.txt
----
*NB*: JDK 11 does not contain a *jre* subdirectory and, neither does a pure 1.8 JRE
distribution.

==== Output from make-update-alternates-for-java help:
----
Name:
  make-alternatives-for-java.

Synopsis:
  make-alternatives-for-java.sh
          [-i] [-s] [-a] [-r] [-p n] [-t target] [-d] [-h] java-home-path

Description:
  make-alternatives-for-java.sh: a wrapper for update-alternatives that
  creates and removes the symbolic links comprising the Debian alternatives
  for executables associated with with a Java JDK.

  -i  install alternatives for executables located at
      java-home-path/jre/bin and java-home-directory/bin. Those in
      jre/bin take precedence over those with the same name as those in
      java-home-path/bin.

  -s  switch alternatives for executables to the JDK at
      java-home-path from the current active alternative.

  -a  switch alternatives for executables for the JDK at
      java-home-path to auto mode.

  -r  remove all the alternatives that were installed from java-home-path.

  -p n
      priority.  See man page for update-alternatives.

  -t directory
      the name of the directory where the master link is to be installed.
      Default: /usr/local/bin

  -n  Perform a "dry run" by echoing the commands that would be performed.

  -h  Show this text.

  java-home-path

  Directories of interest that concern update-alternatives:
  /etc/alternatives /var/lib/dkpg/var/lib/dpkg/alternatives
----

==== Examples:
Make alternatives for jdk1.8.0
----
$ ./make-alternatives-for-java.sh -i /opt/java/jdk1.8.0
    *** WARNING ***
      Alternatives for JREs/JDKs may contain executables that may exist in
      one and not the other alternative, i.e., JRE/JDK 1.8 vs 11.0.

Installing java alternatives for /opt/java/jdk1.8.0
update-alternatives: using /opt/java/jdk1.8.0/jre/bin/ControlPanel to provide /usr/local/bin/ControlPanel (ControlPanel) in auto mode
update-alternatives: using /opt/java/jdk1.8.0/jre/bin/java to provide /usr/local/bin/java (java) in auto mode
update-alternatives: using /opt/java/jdk1.8.0/jre/bin/javaws to provide /usr/local/bin/javaws (javaws) in auto mode
update-alternatives: using /opt/java/jdk1.8.0/jre/bin/jcontrol to provide /usr/local/bin/jcontrol (jcontrol) in auto mode
update-alternatives: using /opt/java/jdk1.8.0/jre/bin/jjs to provide /usr/local/bin/jjs (jjs) in auto mode
      .
      .
      .
----
Let's see what we have:
----
$ update-alternatives --get-selections | egrep 'jdk\.1\.8'
appletviewer                   auto     /opt/java/jdk1.8.0/bin/appletviewer
ControlPanel                   auto     /opt/java/jdk1.8.0/jre/bin/ControlPanel
extcheck                       auto     /opt/java/jdk1.8.0/bin/extcheck
idlj                           auto     /opt/java/jdk1.8.0/bin/idlj
jar                            auto     /opt/java/jdk1.8.0/bin/jar
jarsigner                      auto     /opt/java/jdk1.8.0/bin/jarsigner
java                           auto     /opt/java/jdk1.8.0/jre/bin/java
javac                          auto     /opt/java/jdk1.8.0/bin/javac
javadoc                        auto     /opt/java/jdk1.8.0/bin/javadoc
javafxpackager                 auto     /opt/java/jdk1.8.0/bin/javafxpackager
.
.
.
unpack200                      auto     /opt/java/jdk1.8.0/jre/bin/unpack200
wsgen                          auto     /opt/java/jdk1.8.0/bin/wsgen
wsimport                       auto     /opt/java/jdk1.8.0/bin/wsimport
xjc                            auto     /opt/java/jdk1.8.0/bin/xjc----
----
Make alternatives for JDK11 at a higher priority than 20 which is the default:
----
$ ./make-alternatives-for-java.sh -i -p 40 /opt/java/jdk11.0
    *** WARNING ***
      Alternatives for JREs/JDKs may contain executables that may exist in
      one and not the other alternative, i.e., JRE/JDK 1.8 vs 11.0.

Installing java alternatives for /opt/java/jdk11.0
update-alternatives: using /opt/java/jdk11.0/bin/jaotc to provide /usr/local/bin/jaotc (jaotc) in auto mode
update-alternatives: using /opt/java/jdk11.0/bin/jar to provide /usr/local/bin/jar (jar) in auto mode
update-alternatives: using /opt/java/jdk11.0/bin/jarsigner to provide /usr/local/bin/jarsigner (jarsigner) in auto mode-alternatives: using /opt/java/jdk11.0/bin/javac to provide /usr/local/bin/javac (javac) in auto mode
update-alternatives: using /opt/java/jdk11.0/bin/javadoc to provide /usr/local/bin/javadoc (javadoc) in auto mode
.
.
.
update-alternatives: using /opt/java/jdk11.0/bin/serialver to provide /usr/local/bin/serialver (serialver) in auto mode
update-alternatives: using /opt/java/jdk11.0/bin/unpack200 to provide /usr/local/bin/unpack200 (unpack200) in auto mode
update-alternatives: using /opt/java/jdk11.0/lib/jexec to provide /usr/local/bin/jexec (jexec) in auto mode
----
Check the install:
----
$ update-alternatives --get-selections | egrep jdk11
aotc                          auto     /opt/java/jdk11.0/bin/jaotc
jar                            auto     /opt/java/jdk11.0/bin/jar
jarsigner                      auto     /opt/java/jdk11.0/bin/jarsigner
java                           auto     /opt/java/jdk11.0/bin/java
javac                          auto     /opt/java/jdk11.0/bin/javac
.
.
.
rmiregistry                    auto     /opt/java/jdk11.0/bin/rmiregistry
serialver                      auto     /opt/java/jdk11.0/bin/serialver
unpack200                      auto     /opt/java/jdk11.0/bin/unpack200
----
How many alternatives for the java command:
----
update-alternatives --list java
/opt/java/jdk1.8.0/jre/bin/java
/opt/java/jdk11.0/bin/java
----
Display informations about the link group which name is the master link:
----
update-alternatives --display java
java - auto mode
  link best version is /opt/java/jdk11.0/bin/java
  link currently points to /opt/java/jdk11.0/bin/java
  link java is /usr/local/bin/java
  slave java.1 is /usr/local/man/man1/java.1
/opt/java/jdk1.8.0/jre/bin/java - priority 20
  slave java.1: /opt/java/jdk1.8.0/man/man1/java.1
/opt/java/jdk11.0/bin/java - priority 40
  slave java.1: /opt/java/jdk11.0/man/man1/java.1
----
Reassure ourselves of which java is the default:
----
$ java -version
openjdk version "11.0.8" 2020-07-14 LTS
OpenJDK Runtime Environment (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM (build 11.0.8+10-LTS, mixed mode)
----
MAN page?
----
$ man java

java(1)                                                         Basic Tools                                                         java(1)

NAME
       java - Launches a Java application.

SYNOPSIS
           java [options] classname [args]

           java [options] -jar filename [args]
----
We are good to go.  It is JDK 11 because we installed at a higher priority.

xjc is missing in JDK11 as explained above. Let's see what's what:
----
update-alternatives --display xjc
xjc - auto mode
  link best version is /opt/java/jdk1.8.0/bin/xjc
  link currently points to /opt/java/jdk1.8.0/bin/xjc
  link xjc is /usr/local/bin/xjc
  slave xjc.1 is /usr/local/man/man1/xjc.1
/opt/java/jdk1.8.0/bin/xjc - priority 20
  slave xjc.1: /opt/java/jdk1.8.0/man/man1/xjc.1
----
It is still there as expected.

Let's switch to JDK 1.8:
----
./make-alternatives-for-java.sh -s /opt/java/jdk1.8.0
    *** WARNING ***
      Alternatives for JREs/JDKs may contain executables that may exist in
      one and not the other alternative, i.e., JRE/JDK 1.8 vs 11.0.

Switching java alternatives to /opt/java/jdk1.8.0
/opt/java/jdk11.0/bin/java -> update-alternatives --force --set java /opt/java/jdk1.8.0/jre/bin/java
/opt/java/jdk11.0/bin/jjs -> update-alternatives --force --set jjs /opt/java/jdk1.8.0/jre/bin/jjs
/opt/java/jdk11.0/bin/keytool -> update-alternatives --force --set keytool /opt/java/jdk1.8.0/jre/bin/keytool
/opt/java/jdk11.0/bin/pack200 -> update-alternatives --force --set pack200 /opt/java/jdk1.8.0/jre/bin/pack200
----
Recall it is at priority 20 and JDK 11 is at 40 but the --force switch above
does the trick as shown below:
----
update-alternatives --display java
java - manual mode
  link best version is /opt/java/jdk11.0/bin/java
  link currently points to /opt/java/jdk1.8.0/jre/bin/java
  link java is /usr/local/bin/java
  slave java.1 is /usr/local/man/man1/java.1
/opt/java/jdk1.8.0/jre/bin/java - priority 20
  slave java.1: /opt/java/jdk1.8.0/man/man1/java.1
/opt/java/jdk11.0/bin/java - priority 40
  slave java.1: /opt/java/jdk11.0/man/man1/java.1
----
And confirmed by:
----
java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
----
To go back to JDK 11 which is at a higher priority than 1.8 -- just switch to
auto mode:
----
/make-alternatives-for-java.sh -a /opt/java/jdk1.8.0
Switchingjava alternatives for /opt/java/jdk1.8.0 to auto mode
update-alternatives: using /opt/java/jdk11.0/bin/java to provide /usr/local/bin/java (java) in auto mode
update-alternatives: using /opt/java/jdk11.0/bin/jjs to provide /usr/local/bin/jjs (jjs) in auto mode
update-alternatives: using /opt/java/jdk11.0/bin/keytool to provide /usr/local/bin/keytool (keytool) in auto mode
----
And the result:
----
update-alternatives --display java
java - auto mode
  link best version is /opt/java/jdk11.0/bin/java
  link currently points to /opt/java/jdk11.0/bin/java
  link java is /usr/local/bin/java
  slave java.1 is /usr/local/man/man1/java.1
/opt/java/jdk1.8.0/jre/bin/java - priority 20
  slave java.1: /opt/java/jdk1.8.0/man/man1/java.1
/opt/java/jdk11.0/bin/java - priority 40
  slave java.1: /opt/java/jdk11.0/man/man1/java.1
----

*And that's all folks!*
